data:
  run_id: 0
  antimicrobial: "amikacin"
  labels: "/pvol/data/ast_data_filter_duplicates_041223.csv"
  root_dir: "/pvol/data/extracted_feats/kmer/combined_kmers"
  input_dir: "${data.root_dir}/${data.run_id}/${data.antimicrobial}"
  id_root_dir: "z"
  train_ids: "${data.id_root_dir}/${data.run_id}/${data.antimicrobial}_train.ids"
  val_ids: "${data.id_root_dir}/${data.run_id}/${data.antimicrobial}_val.ids"
  test_ids: "${data.id_root_dir}/${data.run_id}/${data.antimicrobial}_test.ids"
  dist_matrix_1: "/pvol/data/distances/fcgr_7mer_dist.csv"
  dist_matrix_2: "/pvol/data/distances/merged_snp_dist.csv"
  is_dist_1: True
  is_dist_2: True
  retaining_pmille: 2
  use_decoupling: False
  decoupling_matrix: "/pvol/data/mlst_decoupling_mat.csv"
  no_edge: False
  save_adj_matrix: False

preexisting_adj_matrix:
  is_use: False
  root_dir_1: "/pvol/data/adj_mats/fcgr_7mer"
  root_dir_2: "/pvol/data/adj_mats/merged_snp"
  prefix: "permille"
  file_path_1: "${preexisting_adj_matrix.root_dir_1}/${data.antimicrobial}/${preexisting_adj_matrix.prefix}_${data.retaining_pmille}.csv"
  file_path_2: "${preexisting_adj_matrix.root_dir_2}/${data.antimicrobial}/${preexisting_adj_matrix.prefix}_${data.retaining_pmille}.csv"

gnn:
  model_name: "GNN"
  layer_name: "GCN"
  use_feature_encoder: False
  num_layers: 2
  c_hidden: 128
  c_out: 1
  dp_rate: 0.5
  middle_layer: "concat"
  GAT:
    heads: 8
  TransformerConv:
    heads: 8

trainer:
  seed: 222
  default_root_dir: "/mnt/experiments"
  max_epochs: 200
  accelerator: "auto"
  devices: "auto"
  accumulate_grad_batches: 1
  num_nodes: 1
  strategy: "auto"
  precision: 32
  model_checkpoint:
    dirpath: "${trainer.default_root_dir}/out/${trainer.logger.project_prefix}_${trainer.logger.name_prefix}/${data.antimicrobial}/${data.run_id}/"
    monitor: "val_loss"
    mode: "min"
    save_last: False
    save_top_k: 1
  logger:
    save_dir: "${trainer.default_root_dir}/logger/${data.antimicrobial}/${data.run_id}"
    project_prefix: "multi_wgs"
    project: "${trainer.logger.project_prefix}_${data.antimicrobial}"
    name_prefix: "6mer"
    name: "${trainer.logger.name_prefix}_${data.run_id}"
  del_ckpt: True
